env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules: { "react/prop-types": 0,
          "no-restricted-globals": ["error", "event", "fdescribe"],
          "no-unused-vars": ["error",
                            {
                              varsIgnorePattern: "React"
                            }
                          ]
                        }